Pr.pkg.spdlog
ingenue/hunter pull request #280
Opened 2018-10-21 10:58 UTC by fantasticfears

* I have checked that this pull request contains only
  `.travis.yml`/`appveyor.yml` changes. All other changes send
  to https://github.com/ruslo/hunter. **Yes**

* I have checked that no toolchains removed from CI configs, they are commented
  out instead so other developers can enable them back easily and to simplify
  merge conflict resolution. **Yes**

* I have checked that for every commented out toolchain there is a link to the
  broken CI build page or to the minimum compiler requirements documentation
  so other developers can figure out what was the problem exactly. **Yes**

* I have checked that for every enabled toolchain corresponding package passed
  all stages of update cycle: test/merge/upload/release. **Yes**

2018-10-21 12:41 UTC, ruslo requested changes

2018-10-21 12:41 UTC, ruslo commented on examples/spdlog/foo.cpp
> +#include <spdlog/sinks/stdout_sinks.h>
> I have checked that this pull request contains only
.travis.yml/appveyor.yml changes. All other changes send
to https://github.com/ruslo/hunter. Yes

Please send this to https://github.com/ruslo/hunter :
* https://github.com/ruslo/hunter/blob/v0.23.34/examples/spdlog/foo.cpp#L1-L6

I guess it should be part of https://github.com/ruslo/hunter/pull/1588

2018-10-21 15:24 UTC, erickguan commented on examples/spdlog/foo.cpp
> +#include <spdlog/sinks/stdout_sinks.h>
Good point. I was lost in branches. This PR is rebased. The other PR gets cherry-picked commit.

2018-10-22 11:53 UTC, ruslo approved these changes

2018-10-22 11:57 UTC, merged