merge pkg.template into pkg.mysqlclient
ingenue/hunter pull request #287
Opened 2018-11-01 20:07 UTC by caseymcc

This is a pkg.template merge, not sure how they are handled in general

2018-11-02 09:31 UTC, ruslo requested changes
> Conflicting files
> .travis.yml
> appveyor.yml

Can't do the merge because of conflicts.

2018-11-02 09:31 UTC, ruslo commented on appveyor.yml
> +    - TOOLCHAIN: "vs-14-2015-win64"
It's `vs-14-2015-sdk-8-1`, not `vs-14-2015-win64`:
* https://github.com/ingenue/hunter/blob/3650bcbc792940034cdbad7f7f05051dd5f1f68c/appveyor.yml#L23-L25

If you want to change toolchain then it's better to comment out default one and add another to the bottom.

2018-11-02 15:19 UTC, caseymcc commented
I don't understand why there is a merge problem to begin with. I resolved the merge problem when I merged the pkg.template branch then updated updated the files with another commit. Shouldn' t the merge already be resolved?

2018-11-02 15:29 UTC, caseymcc commented
Needs updated mysql https://github.com/ruslo/hunter/pull/1605, in order to test CI

2018-11-06 19:16 UTC, ruslo commented
> I don't understand why there is a merge problem to begin with. I resolved the merge problem when I merged the pkg.template branch then updated the files with another commit. Shouldn' t the merge already be resolved? Why do I have to resolve it again on github?

Sounds like a right path, hard to say what went wrong without details.

> Needs updated mysql ruslo#1605, in order for CI to pass.

If your patch fix some issues you should test it against old toolchains first, then add new toolchains after merge, see:
* https://docs.hunter.sh/en/latest/creating-new/update.html#add-toolchains

2018-11-07 20:01 UTC, caseymcc commented
Updates the test to include the originals before the merge

https://travis-ci.org/caseymcc/hunter/builds/452039939
https://ci.appveyor.com/project/caseymcc/hunter/builds/20126897

2018-11-07 20:03 UTC, ruslo requested changes
> Conflicting files
> .travis.yml
> appveyor.yml

I can't merge

2018-11-07 20:49 UTC, caseymcc commented
fixed the merge, still not sure why it is happening.

2018-11-07 21:06 UTC, ruslo requested changes

2018-11-07 21:06 UTC, ruslo commented on .travis.yml
> +        TOOLCHAIN=default
There is no `default` toolchain in testing table:
* https://github.com/ingenue/hunter/blob/6cf263ab8d7ed931de20ef210a353940ad4c6b36/.travis.yml#L36-L69

It was removed a long time ago...

2018-11-07 21:12 UTC, ruslo commented
I have updated branch, testing:
* https://ci.appveyor.com/project/ingenue/hunter/builds/20129988
* https://travis-ci.org/ingenue/hunter/builds/452093991?utm_source=github_status&utm_medium=notification

2018-11-07 21:12 UTC, closed without merging