Pkg.suitesparse merge pkg.template
ingenue/hunter pull request #289
Opened 2018-11-13 16:46 UTC by NeroBurner

This PR updates the toolchains to the current pkg.template branch and enables some failing tests. Those failing tests are disabled in the branch [test.suitesparse](https://github.com/NeroBurner/hunter/tree/test.suitesparse) with the following two commits
- https://github.com/NeroBurner/hunter/commit/047d12faf8b64671ce15589432977b7164856046
- https://github.com/NeroBurner/hunter/commit/e459579f95cc010f1a3ef024c8e82a4a30d9028b

shall I add those commits to this PR?

* I have checked that this pull request contains only
  `.travis.yml`/`appveyor.yml` changes. All other changes send
  to https://github.com/ruslo/hunter. **[Yes]**

* I have checked that no toolchains removed from CI configs, they are commented
  out instead so other developers can enable them back easily and to simplify
  merge conflict resolution. **[Yes]**

* I have checked that for every commented out toolchain there is a link to the
  broken CI build page or to the minimum compiler requirements documentation
  so other developers can figure out what was the problem exactly. **[No]**
  OSX toolchains break because of missing Fortran compiler, only one linked

* I have checked that for every enabled toolchain corresponding package passed
  all stages of update cycle: test/merge/upload/release. **[Yes]**

2018-11-13 16:56 UTC, ruslo commented
> shall I add those commits to this PR?

Yes. Disable toolchains, then add new version, see:
* https://docs.hunter.sh/en/latest/creating-new/update.html#remove-toolchains

2018-11-13 17:10 UTC, ruslo requested changes

2018-11-13 17:10 UTC, ruslo commented on .travis.yml
> +        TOOLCHAIN=ios-nocodesign-11-3-dep-9-3
Please use `ios-nocodesign-11-4-dep-9-3`:
* https://github.com/ingenue/hunter/blob/ac176586f038f37e7d5909b8ad079ed5aae28fd0/.travis.yml#L87-L91

2018-11-13 17:10 UTC, ruslo commented on .travis.yml
> +      osx_image: xcode9.3
Please use `osx_image: xcode 9.4`:
* https://github.com/ingenue/hunter/blob/ac176586f038f37e7d5909b8ad079ed5aae28fd0/.travis.yml#L75-L79

2018-11-14 08:01 UTC, ruslo requested changes

2018-11-14 08:01 UTC, ruslo commented on .travis.yml
> +    - os: linux
If this toolchain is working now, then `FIXME` can be removed.

2018-11-14 08:01 UTC, ruslo commented on .travis.yml
> +    - os: linux
Remove `FIXME`?

2018-11-14 08:01 UTC, ruslo commented on .travis.yml
> +    #    TOOLCHAIN=ios-nocodesign-11-3-dep-9-3
`TOOLCHAIN=ios-nocodesign-11-4-dep-9-3`

2018-11-14 10:15 UTC, NeroBurner commented
thanks for the fast response, removed old FIXME, updated xcode toolchain

2018-11-14 10:33 UTC, ruslo approved these changes

2018-11-14 11:23 UTC, merged