Pkg.wdc
ingenue/hunter pull request #327
Opened 2019-01-04 21:29 UTC by rusdevops

* I have checked that this pull request contains only
  `.travis.yml`/`appveyor.yml` changes. All other changes send
  to https://github.com/ruslo/hunter. **[No]**

* I have checked that no toolchains removed from CI configs, they are commented
  out instead so other developers can enable them back easily and to simplify
  merge conflict resolution. **[Yes]**

* I have checked that for every commented out toolchain there is a link to the
  broken CI build page or to the minimum compiler requirements documentation
  so other developers can figure out what was the problem exactly. **[Yes]**

* I have checked that for every enabled toolchain corresponding package passed
  all stages of update cycle: test/merge/upload/release. **[Yes]**

2019-01-04 21:44 UTC, rusdevops commented
appveyor :ok:: https://ci.appveyor.com/project/rusdevops/hunter/builds/21392906
travis :ok:: https://travis-ci.org/rusdevops/hunter/builds/475500957

2019-01-05 08:11 UTC, rusdevops commented
Updated!

2019-01-10 05:31 UTC, ruslo requested changes

2019-01-10 05:31 UTC, ruslo commented on cmake/configs/default.cmake
> +hunter_default_version(WDC VERSION 1.1.5)
This change and in particular https://github.com/ingenue/hunter/pull/327/commits/082a56d93cf10338c2dae51af284032cb940cc1b commit don't belong here, please send it to https://github.com/ruslo/hunter

> I have checked that this pull request contains only
> .travis.yml/appveyor.yml changes. All other changes send
> to https://github.com/ruslo/hunter. [**No**]

It's expected that you will answer **Yes** here.

See also: https://docs.hunter.sh/en/latest/creating-new/update.html#add-toolchains

2019-01-10 06:24 UTC, ruslo commented
Branch `pkg.wdc` updated:
* https://ci.appveyor.com/project/ingenue/hunter/builds/21513601
* https://travis-ci.org/ingenue/hunter/builds/477676055?utm_source=github_status&utm_medium=notification

2019-01-10 06:24 UTC, closed without merging

2019-01-10 07:26 UTC, rusdevops commented on cmake/configs/default.cmake
> +hunter_default_version(WDC VERSION 1.1.5)
I send pull request: https://github.com/ruslo/hunter/pull/1698