Remove Android comments
ingenue/hunter pull request #34
Opened 2016-10-20 06:59 UTC by xsacha

2016-10-20 10:50 UTC, ruslo commented
I forget to update pkg.openssl branch, sorry. Please rebase.

2016-10-20 23:12 UTC, xsacha commented
Rebased

2016-10-21 00:18 UTC, xsacha commented
Failure: https://travis-ci.org/ingenue/hunter/jobs/169389003
Has the old error about HAVE_POLL_FINE_EXITCODE not being set. Code not updated?

2016-10-21 00:20 UTC, ruslo requested changes

2016-10-21 00:20 UTC, ruslo commented on .travis.yml
> +      env: PROJECT_DIR=examples/OpenSSL TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
Not working: https://travis-ci.org/ingenue/hunter/jobs/169384946

2016-10-21 00:22 UTC, ruslo commented
> Has the old error about HAVE_POLL_FINE_EXITCODE not being set. Code not updated?

As far as I remember that was about CURL, no?

2016-10-21 01:52 UTC, ruslo approved these changes

2016-10-21 06:24 UTC, merged

2016-10-21 06:28 UTC, ruslo commented
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1108
* https://travis-ci.org/ingenue/hunter/builds/169449967