Test 'ncursesw' package
ingenue/hunter pull request #379
Opened 2019-07-03 05:06 UTC by tstack

* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://travis-ci.org/tstack/hunter/builds/553429479

* My change will resolve this "New package" request: https://github.com/ruslo/hunter/issues/1739

---

2019-07-03 12:09 UTC, ruslo requested changes

2019-07-03 12:09 UTC, ruslo commented on .travis.yml
> +        PROJECT_DIR=examples/ncursesw
>  Here is the links to the Travis/AppVeyor with status "All passed":

iOS toolchain is failing:
- https://travis-ci.org/tstack/hunter/jobs/553429491

Please exclude it. Exclude other failing toolchains too.

2019-07-04 05:38 UTC, tstack commented
Here's an updated build on my fork with the broken toolchains commented out:

  * https://travis-ci.org/tstack/hunter/builds/554072871

2019-07-04 08:23 UTC, ruslo commented
> Here's an updated build on my fork with the broken toolchains commented out:

Thanks.

If there is no working toolchain in `appveyor.yml`, please exclude all toolchains there and add `dummy` one, example:
- https://github.com/ingenue/hunter/blob/b52b18e7ac51cec76c63a61dd81195c5bfc2a160/appveyor.yml#L35-L41

2019-07-04 14:50 UTC, tstack commented
Added the dummy toolchain in appveyor :

  * https://ci.appveyor.com/project/tstack/hunter/builds/25752024

2019-07-04 14:51 UTC, tstack commented
(Accidentally hit the close button)

2019-07-05 07:19 UTC, ruslo requested changes
> Added the dummy toolchain in appveyor 

Please add it to this pull request.

2019-07-05 14:58 UTC, tstack commented
Sorry, didn't push the pr branch.

2019-07-05 15:11 UTC, ruslo approved these changes

2019-07-05 15:11 UTC, merged