Czmq testing
ingenue/hunter pull request #42
Opened 2016-12-05 13:40 UTC by ErniBrown

As requested in #603, I checked the travis and appveyor builds. The offending task where all related to ZeroMQ build, so i almost copied zeromq testing branch.
Please note that ZeroMQ is actually not able to build with an external toolchain.

2016-12-05 13:48 UTC, ruslo requested changes

2016-12-05 13:48 UTC, ruslo commented on .travis.yml
> +    # FIXME:
Please leave some info about problem. At least the link to the broken Travis job.

2016-12-05 13:48 UTC, ruslo commented on appveyor.yml
> -    - TOOLCHAIN: "ninja-vs-12-2013-win64"
Please comment each toolchain instead of deleting them. If somebody want to fix anything he will be able to un-comment them one by one.

2016-12-05 13:48 UTC, ruslo commented on cmake/configs/default.cmake
> +hunter_config(czmq VERSION 4.0.1-p0)
Doesn't belong here, see README:
* https://github.com/ingenue/hunter

2016-12-05 13:50 UTC, ruslo commented
> note that ZeroMQ is actually not able to build with an external toolchain

All this builds use external toolchain from Polly:
* https://travis-ci.org/ingenue/hunter/builds/119767217

So I guess it's not true :)

2016-12-05 14:05 UTC, ErniBrown commented
With android toolchain, and at least with a linaro derived toolchain I'm working with, the crosscompiling fails due to TRY_RUN errors:
```
-- Checking whether SO_KEEPALIVE is supported
-- Performing Test ZMQ_HAVE_SO_KEEPALIVE
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   ZMQ_HAVE_SO_KEEPALIVE_EXITCODE (advanced)
For details see /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/a7d98bd/b06c3ce/cab2b21/Build/ZeroMQ/Build/ZeroMQ-Release-prefix/src/ZeroMQ-Release-build/TryRunResults.cmake
-- Performing Test ZMQ_HAVE_SO_KEEPALIVE - Failed
```
That's the reason why android test is disabled in pkg.zeromq

This can be fixed by manually setting the expected result in cache. I was able to do so for the hunter package of ZeroMQ only creating a custom scheme, which is not a great solution. Is there a proper way to set a "Hunter cache" variable?

2016-12-05 14:21 UTC, ruslo commented
> Is there a proper way to set a "Hunter cache" variable?

I think they can be added by custom `CMAKE_ARGS`:
* https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-cmake-options

@ErniBrown if you're planning to fix zeromq please do it separately from czmq.

2016-12-05 15:06 UTC, ErniBrown commented on cmake/configs/default.cmake
> +hunter_config(czmq VERSION 4.0.1-p0)
Ok, I don't get it, how can i test czmq package, if czmq package is not part of hunter?
Where and how should i set version for CI?

2016-12-05 15:41 UTC, ruslo commented on cmake/configs/default.cmake
> +hunter_config(czmq VERSION 4.0.1-p0)
tl;dr just follow the [rules](https://github.com/ingenue/hunter) blindly and everything will be ok :)

the path of changes is `hunter/develop` -> `ingenue/pkg.template` -> `ingenue/pkg.*` -> `ingenue/upload.*`. All "regular" changes should go to `hunter/develop`, all package-specific CI configuration (i.e. `.travis.yml`/`appveyor.yml`) should go to `ingenue/pkg.*`. I will take care of the rest. For now [pkg.czmq](https://travis-ci.org/ingenue/hunter/builds/180869545) branch contains only of CI configuration without real example so it has "red" state, hence it's okay that your pull request will not make it "green" (you're not breaking working stuff).

2017-04-05 10:35 UTC, ruslo requested changes

2017-04-05 10:35 UTC, ruslo commented on cmake/projects/czmq/hunter.cmake
> +# !!! DO NOT PLACE HEADER GUARDS HERE !!!
Please remove this file, only `.travis.yml` or `appveyor.yml` changes:
* https://github.com/ingenue/hunter

2017-04-10 12:56 UTC, ruslo approved these changes

2017-04-10 12:57 UTC, merged