Updated test package.
ingenue/hunter pull request #44
Opened 2016-12-05 15:08 UTC by caseymcc

Removed support for Android as it should be linked from the NDK.
Removed support for Apple as OpenCL support stops at 1.2
Removed VC 9-10 as the headers contain some code that they don't understand.
Removed MinGW on windows as it links to the native direct x which has some VC specific code that gcc does not understand.

2016-12-05 15:16 UTC, caseymcc commented
Something wrong in the merge looking into it.

2016-12-05 15:41 UTC, caseymcc commented
Looks like test are passing, assuming everything else is good, this should be good to go.

2016-12-05 15:45 UTC, ruslo requested changes

2016-12-05 15:45 UTC, ruslo commented on .travis.yml
> -      env: PROJECT_DIR=examples/OpenCL TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
Please leave some info about build. At least link to the broken job.

2016-12-05 15:45 UTC, ruslo commented on cmake/configs/default.cmake
> +hunter_config(OpenCL VERSION 2.1-p0)
It doesn't belong here, see [README](https://github.com/ingenue/hunter). Just wrote some info: https://github.com/ingenue/hunter/pull/42#discussion_r90889722

2016-12-05 15:51 UTC, caseymcc commented on cmake/configs/default.cmake
> +hunter_config(OpenCL VERSION 2.1-p0)
I was a bit confused about how the test were being run without this, guess a little reading pays off. I am assuming example code needs to be removed as well?

2016-12-05 15:52 UTC, caseymcc commented on .travis.yml
> -      env: PROJECT_DIR=examples/OpenCL TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
Not sure what you mean? Do you want me to comment out the tool chain and add a remark as to why it is not run?

2016-12-05 16:08 UTC, caseymcc commented
I think I have made the changes you wanted.

2016-12-05 16:13 UTC, ruslo commented on .travis.yml
> -      env: PROJECT_DIR=examples/OpenCL TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
Here is the link to the broken job:
* https://travis-ci.org/ingenue/hunter/jobs/180306953

Add it as a comment so if somebody want to take a look at the problem.

2016-12-05 16:26 UTC, caseymcc commented
Added links to failed toolchains.

2016-12-06 11:09 UTC, ruslo approved these changes

2016-12-06 11:09 UTC, merged