Test MySQL against Windows now
ingenue/hunter pull request #58
Opened 2017-04-06 14:30 UTC by caseymcc

2017-04-06 15:23 UTC, ruslo requested changes

2017-04-06 15:23 UTC, ruslo commented on .travis.yml
> +    # FIXME: https://travis-ci.org/caseymcc/hunter/jobs/218630987
What changed here?

2017-04-06 15:24 UTC, ruslo commented
Will test this first:
* https://github.com/ruslo/hunter/pull/755

Then if everything is okay (we don't break old stuff), we can add new toolchains.

2017-04-06 16:52 UTC, caseymcc commented on .travis.yml
> +    # FIXME: https://travis-ci.org/caseymcc/hunter/jobs/218630987
probably didn't need to update this, original I thought I had gotten the osx-10-9 toolchain working so I made changes to the file with the intention to updating.

2017-04-11 02:26 UTC, ruslo commented
> Will test this first

Looks good now, merged. Branch `pkg.mysqlclient` updated, please rebase this patch so we can test latest version.

2017-04-11 13:54 UTC, caseymcc commented
Should be good now

2017-04-11 15:39 UTC, ruslo approved these changes

2017-04-11 15:40 UTC, merged