Pr.libuv.excludes
ingenue/hunter pull request #60
Opened 2017-04-23 14:24 UTC by akalsi87

2017-04-23 14:43 UTC, ruslo requested changes
Please squash your changes into one commit.

2017-04-23 14:43 UTC, ruslo commented on cmake/configs/default.cmake
> +  hunter_config(jsoncpp VERSION 1.8.0)
This doesn't belong here. Only `.travis.yml`/`appveyor.yml`, see README:
* https://github.com/ingenue/hunter

2017-04-23 17:00 UTC, ruslo commented
> Please squash your changes into one commit.

There are still two commits...

2017-04-26 21:58 UTC, akalsi87 commented
I tried but it says I have merge conflicts, and that's why I had two commits last time as well. help please @ruslo

2017-04-27 00:37 UTC, ruslo commented
> help please @ruslo

Fetch branch `pkg.libuv`, exclude toolchains and push changes. What kind of problems can appear here? It's kind of trivial...

2017-04-27 23:56 UTC, closed without merging