Libuv CI
ingenue/hunter pull request #64
Opened 2017-04-28 11:52 UTC by twiddle-bits

Libuv CI

2017-04-28 12:35 UTC, ruslo requested changes

2017-04-28 12:35 UTC, ruslo commented on .travis.yml
> +addons:
Doesn't belong here.

2017-04-30 12:17 UTC, twiddle-bits commented
@ruslo This is fixed.

2017-04-30 12:48 UTC, ruslo approved these changes

2017-04-30 12:48 UTC, merged