adding pugixml package
ingenue/hunter pull request #95
Opened 2017-07-24 23:15 UTC by rusdevops

2017-07-25 09:59 UTC, ruslo requested changes

2017-07-25 09:59 UTC, ruslo commented on cmake/configs/default.cmake
> +hunter_config(pugixml VERSION 1.8.1)
Doesn't belong here. Only `.travis.yml`/`appveyor.yml` patches. See README:
* https://github.com/ingenue/hunter

You can find some useful info in this issue:
* https://github.com/ruslo/hunter/issues/743

2017-07-26 01:57 UTC, rusdevops commented
I fixed in #100.

2017-07-26 05:16 UTC, ruslo commented
Closing for https://github.com/ingenue/hunter/pull/100

2017-07-26 05:16 UTC, closed without merging